Tls Fastly resources added
aws-ia/cloudformation-fastly-resource-providers pull request #11
Opened 2022-12-12 12:52 UTC by lukiwlosek

2022-12-21 16:07 UTC, joshuadeanhall requested changes

2022-12-21 16:07 UTC, joshuadeanhall commented on Fastly-Tls-Certificate/fastly-tls-certificate.json
> +    "description": "An example resource schema demonstrating some basic constructs and validation rules.",
Could we update the description

2022-12-21 16:07 UTC, joshuadeanhall commented on Fastly-Tls-Certificate/fastly-tls-certificate.json
> +    "sourceUrl": "https://github.com/aws-cloudformation/aws-cloudformation-rpdk.git",
Can we replace the sourceUrl with the url for this repo?

2022-12-21 16:07 UTC, joshuadeanhall commented on Fastly-Tls-Domain/fastly-tls-domain.json
> +    "description": "An example resource schema demonstrating some basic constructs and validation rules.",
Could we update the description and sourceURL of this resource also.

2022-12-21 16:07 UTC, joshuadeanhall commented on Fastly-Tls-PrivateKeys/fastly-tls-privatekeys.json
> +    "description": "An example resource schema demonstrating some basic constructs and validation rules.",
Can we update the description and sourceURL for this resource also.

2022-12-22 09:03 UTC, tbouron requested changes
@lukiwlosek Looks good! There are just few snags I found, see below

2022-12-22 09:03 UTC, tbouron commented on Fastly-Tls-PrivateKeys/jest.config.ts
> +};
Same as above

2022-12-22 09:03 UTC, tbouron commented on Fastly-Tls-PrivateKeys/fastly-tls-privatekeys.json
> +        },
This should be removed as the resource update handle throws a `exceptions.NotUpdatable();`

2022-12-22 09:54 UTC, lukiwlosek commented on Fastly-Tls-Certificate/inputs/inputs_1_update.json
> +        "Name": "Tls name"
Cannot test as Attributes is an object, and there is an issue with ctv where we cannot update nested objects unfortunately

2022-12-22 18:07 UTC, joshuadeanhall approved these changes

2022-12-22 18:07 UTC, merged